name: Check Code

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs at 16:00 UTC (BeiJing 00:00) on the 1st of every month
  schedule:
    - cron:  '0 16 1 * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-license-lines:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Checkout new file
      shell: bash
      run: |
        git --version
        git branch
        git reset origin/master --soft
        git status

    - name: Check License Lines
      uses: kt3k/license_checker@v1.0.6
