name: "auto sync gitee_master"
on:
  # Runs at 16:00 UTC (BeiJing 00:00) on the 1st of every month
  schedule:
    - cron:  '0 16 1 * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
        
      - name: Setup Deploy Private Key
        env:
          LOCAL_PRIVATE_KEY: ${{ secrets.LOCAL_PRIVATE_KEY }}
        run: |
          git --version
          mkdir -p ~/.ssh/
          echo "$LOCAL_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Pull request
        shell: bash
        run: |
          git config --global user.name  'thread-liu'
          git config --global user.email 'lk9608@outlook.com' 
          git remote add rtt_github https://github.com/RT-Thread/rt-thread
          git remote add rtt_gitee https://gitee.com/rtthread/rt-thread
          git fetch rtt_github master:rtt_github
          git fetch rtt_gitee gitee_master:rtt_gitee
          git checkout -b localdev rtt_github/master
          git merge rtt_gitee/gitee_master
          git push --force origin localdev:rebot
          git checkout master

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
        
          commit-message: rtthread-bot
          committer: GitHub <thread-liu@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.thread-liu.github.com>
          signoff: false
          base: rebot
          branch: test
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: thread-liu
          reviewers: thread-liu
          team-reviewers: |
            owners
            maintainers
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
