#
# Copyright (c) 2006-2023, RT-Thread Development Team
#
# SPDX-License-Identifier: Apache-2.0
#
# Change Logs:
# Date           Author       Notes
# 2023-07-01     Supperthomas the first version
#
name:  manual_scons_dist_trigger_only_one

# Controls when the action will run. Triggers 'scons --dist' to build the dist
on:
  workflow_dispatch:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
    inputs:
      bsp_options:
        description: 'Which bsp path Would you want dist in bsp?like stm32/stm32l496-st-nucleo '
        required: false
        type: string
        default: 'stm32/stm32l496-st-nucleo'
      bsp_tool_chain:
        description: 'Choice tool_chain'
        required: false
        default: 'sourcery-arm'
        type: choice
        options:
          - "sourcery-arm"
          - "llvm-arm"
          - "sourcery-aarch64"
          - "sourcery-mips"
          - "sourcery-riscv-none-embed"
          - "sourcery-riscv64-unknown-elf"
          - "gcc"
      bsp_config:
        description: 'Type a config you want mannual test in .config, like CONFIG_BSP_USING_I2C CONFIG_BSP_USING_WDT '
        required: false
        type: string
        default: 'CONFIG_BSP_USING_GPIO'
      dist_flag:
        description: 'True to dist all bsp, False not dist'
        required: true
        type: boolean
        default: false

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: self-hosted
    name: ${{ github.event.inputs.bsp_options }}
    steps:
      - uses: actions/checkout@v3
      - name: Bsp Scons Compile
        if: ${{ success() }}
        shell: bash
        env:
          RTT_BSP: ${{ github.event.inputs.bsp_options }}
          RTT_TOOL_CHAIN: ${{ github.event.inputs.bsp_tool_chain}}
        run: |
          source ~/.env/env.sh
          echo $RTT_BSP
          ls bsp/$RTT_BSP/Kconfig && scons -C bsp/$RTT_BSP --pyconfig-silent
          sed -i "s/# ${{ github.event.inputs.bsp_config }} is not set/${{ github.event.inputs.bsp_config }}=y/g" bsp/$RTT_BSP/.config
          pushd bsp/$RTT_BSP && pkgs --update && popd
          cd bsp/$RTT_BSP
          scons --target=mdk5
          UV4.exe -r project.uvprojx -q -j0 -t rt-thread -o test.log
          cat test.log
